// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: envoy_service_config.proto

package controller

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/gogo/protobuf/types"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = types.DynamicAny{}
)

// Validate checks the field values on EnvoyServiceConfig with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *EnvoyServiceConfig) Validate() error {
	if m == nil {
		return nil
	}

	{
		tmp := m.GetRetryPolicy()

		if v, ok := interface{}(tmp).(interface{ Validate() error }); ok {

			if err := v.Validate(); err != nil {
				return EnvoyServiceConfigValidationError{
					field:  "RetryPolicy",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}
	}

	for idx, item := range m.GetHealthChecks() {
		_, _ = idx, item

		{
			tmp := item

			if v, ok := interface{}(tmp).(interface{ Validate() error }); ok {

				if err := v.Validate(); err != nil {
					return EnvoyServiceConfigValidationError{
						field:  fmt.Sprintf("HealthChecks[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					}
				}
			}
		}

	}

	{
		tmp := m.GetTlsContext()

		if v, ok := interface{}(tmp).(interface{ Validate() error }); ok {

			if err := v.Validate(); err != nil {
				return EnvoyServiceConfigValidationError{
					field:  "TlsContext",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}
	}

	return nil
}

// EnvoyServiceConfigValidationError is the validation error returned by
// EnvoyServiceConfig.Validate if the designated constraints aren't met.
type EnvoyServiceConfigValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e EnvoyServiceConfigValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e EnvoyServiceConfigValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e EnvoyServiceConfigValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e EnvoyServiceConfigValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e EnvoyServiceConfigValidationError) ErrorName() string {
	return "EnvoyServiceConfigValidationError"
}

// Error satisfies the builtin error interface
func (e EnvoyServiceConfigValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEnvoyServiceConfig.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = EnvoyServiceConfigValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = EnvoyServiceConfigValidationError{}
